version: "3.9"
services:

  example-core-db:
    container_name: example-core-db
    image: postgres:14.1
    ports:
      - "54340:5432"
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: password
      POSTGRES_DB: example-core-db
    volumes:
      - example-core-db-data:/var/lib/postgres # persist data even if container shuts down

  example-core-keycloak:
    container_name: example-core-keycloak
    depends_on:
      - example-core-keycloak-db
    image: keycloak/keycloak:20.0
    volumes:
      - ./docker/imports/keycloak:/opt/keycloak/data/import/
      - ./docker/imports/keycloak/exports:/opt/keycloak/data/exports
    ports:
      - "8082:8080"
    environment:
      KC_HOSTNAME_URL: http://localhost:8082/auth/
      KC_HOSTNAME_ADMIN_URL: http://localhost:8082/auth/
      KC_HTTP_RELATIVE_PATH: "/auth/"
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://example-core-keycloak-db:5432/keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/auth/health/ready" ]
      interval: 15s
      timeout: 2s
      retries: 15
    command: [ "start --import-realm" ]

  example-core-keycloak-db:
    image: postgres:14.1
    container_name: example-core-keycloak-db
    ports:
      - "54329:5432"
    environment:
      - POSTGRES_USER=${DB_USER:-keycloak}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-keycloak}

volumes:
  example-core-db-data: #enabled persistence
