openapi: 3.0.3
info:
  title: Docsys Document API
  description: API for generating PDF documents from templates with key-value parameters
  version: 1.0.0

paths:
  /documents/{documentId}/generate:
    post:
      summary: Generate PDF synchronously
      description: Generates a PDF document from a template and returns the PDF file immediately
      operationId: generatePdfSync
      tags:
        - PDF Generation
      parameters:
        - name: documentId
          in: path
          required: true
          description: Unique identifier of the document to use
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GeneratePdfRequest'
            examples:
              brief-aankondigig:
                summary: Brief aankondigig
                value:
                  filename: "brief-aankondiging-zaak-01234"
                  parameters:
                    firstName: "Tess"
                    lastName: "Terloops"
                    date: "2025-10-16"
      responses:
        '200':
          description: PDF generated successfully
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  schemas:
    GeneratePdfRequest:
      type: object
      required:
        - parameters
      properties:
        parameters:
          type: object
          description: Key-value pairs for document variables
          additionalProperties:
            type: string
          example:
            firstName: "Tess"

    ErrorResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: Detailed error message
          example: "Invalid document parameters provided"

  responses:
    BadRequest:
      description: Invalid request parameters
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            message: "Invalid document parameters provided"

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            message: "template not found"

    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            message: "An unexpected error occurred"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token for authentication

security:
  - bearerAuth: []
