version: "3.9"
services:

  # GZAC core
  example-core-db:
    container_name: example-core-db
    image: postgres:14.1
    ports:
      - "54340:5432"
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: password
      POSTGRES_DB: example-core-db

  example-core-keycloak:
    container_name: example-core-keycloak
    depends_on:
      - example-core-keycloak-db
    image: keycloak/keycloak:20.0
    volumes:
      - ./docker/imports/keycloak:/opt/keycloak/data/import/
      - ./docker/imports/keycloak/exports:/opt/keycloak/data/exports
    ports:
      - "8082:8080"
    environment:
      KC_HOSTNAME_URL: http://localhost:8082/auth/
      KC_HOSTNAME_ADMIN_URL: http://localhost:8082/auth/
      KC_HTTP_RELATIVE_PATH: "/auth/"
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://example-core-keycloak-db:5432/keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/auth/health/ready" ]
      interval: 15s
      timeout: 2s
      retries: 15
    command: [ "start --import-realm" ]

  example-core-keycloak-db:
    image: postgres:14.1
    container_name: example-core-keycloak-db
    ports:
      - "54329:5432"
    environment:
      - POSTGRES_USER=${DB_USER:-keycloak}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-keycloak}

  gzac-rabbitmq:
    image: rabbitmq:3-management
    container_name: example-gzac-rabbitmq
    volumes:
      - ./docker/imports/gzac-rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./docker/imports/gzac-rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    ports:
      - "5672:5672"
      - "15672:15672"


  # ZGW
  openzaak-redis:
    image: redis:6.2.6
    container_name: example-openzaak-redis
    profiles:
      - zgw
      - openzaak

  openzaak:
    image: openzaak/open-zaak:1.11.0
    container_name: example-openzaak
    platform: linux/amd64
    profiles:
      - zgw
      - openzaak
    environment:
      - DB_HOST=openzaak-database
      - DB_POST=5433
      - SECRET_KEY=veryRestrictedSecretKey
      - DB_USER=openzaak
      - DB_PASSWORD=openzaak
      - DB_NAME=openzaak
      - CACHE_DEFAULT=openzaak-redis:6379/0
      - CACHE_AXES=openzaak-redis:6379/0
      - DEBUG=true
      - ALLOWED_HOSTS=localhost,host.docker.internal,172.17.0.1,openzaak
      - OPENZAAK_SUPERUSER_USERNAME=admin
      - OPENZAAK_SUPERUSER_EMAIL=admin@admin.org
      - DJANGO_SUPERUSER_PASSWORD=admin
      - SENDFILE_BACKEND=django_sendfile.backends.simple
      - NOTIFICATIONS_DISABLED=true
      - CORS_ALLOW_ALL_ORIGINS=True
      - LOG_LEVEL=DEBUG
    ports:
      - "8001:8000"
    depends_on:
      - openzaak-database
      - openzaak-redis

  openzaak-database:
    image: mdillon/postgis:11
    container_name: example-openzaak-database
    platform: linux/amd64
    profiles:
      - zgw
      - openzaak
    environment:
      - POSTGRES_USER=openzaak
      - POSTGRES_PASSWORD=openzaak
      - POSTGRES_DB=openzaak
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5433:5432"
    volumes:
      - ./docker/imports/open-zaak:/docker-entrypoint-initdb.d

  objecten-api:
    image: maykinmedia/objects-api:2.1.1
    container_name: example-objecten-api
    platform: linux/amd64
    profiles:
      - zgw
      - objecten
    ports:
      - "8010:8000"
    environment: &objects-env
      - CORS_ALLOW_ALL_ORIGINS=true
      - SECRET_KEY=${SECRET_KEY:-1(@f(-6s_u(5fd&1sg^uvu2s(c-9sapw)1era8q&)g)h@cwxxg}
      - DJANGO_SETTINGS_MODULE=objects.conf.docker
      - DB_HOST=objecten-api-database
      - DEBUG=true
      - TWO_FACTOR_FORCE_OTP_ADMIN=False # this is not available yet in this version
      - TWO_FACTOR_PATCH_ADMIN=False
    depends_on:
      - objecten-api-database

  objecten-api-database:
    image: postgis/postgis:13-3.1
    container_name: example-objecten-api-database
    platform: linux/amd64
    profiles:
      - zgw
      - objecten
    ports:
      - "54321:5434"
    environment:
      - POSTGRES_USER=objects
      - POSTGRES_PASSWORD=objects
      - POSTGRES_DB=objects

  objecten-api-import:
    image: maykinmedia/objects-api:2.1.1
    container_name: example-objects-api-import
    platform: linux/amd64
    profiles:
      - zgw
      - objecten
    environment: *objects-env
    # in the current version of django it is not possible to create a new user with password without user interaction by using the createsuperuser command
    command: sh init/init.sh
    volumes:
      - ./docker/imports/objects-api/fixtures:/app/src/objects/fixtures
      - ./docker/imports/objects-api/init:/app/init
    depends_on:
      - objecten-api

  objecttypen-api:
    image: maykinmedia/objecttypes-api:2.1.0
    container_name: example-objecttypen-api
    platform: linux/amd64
    profiles:
      - zgw
      - objecten
    ports:
      - "8011:8000"
    environment: &objecttypes-env
      - CORS_ALLOW_ALL_ORIGINS=true
      - SECRET_KEY=${SECRET_KEY:-fgv=c0hz&tl*8*3m3893@m+1pstrvidc9e^5@fpspmg%cy$$15d}
      - DJANGO_SETTINGS_MODULE=objecttypes.conf.docker
      - DB_HOST=objecttypen-api-database
      - DEBUG=true
      - TWO_FACTOR_FORCE_OTP_ADMIN=False # this is not available yet in this version
      - TWO_FACTOR_PATCH_ADMIN=False
    depends_on:
      - objecttypen-api-database

  objecttypen-api-database:
    image: postgres:14.1
    container_name: example-objecttypen-api-database
    profiles:
      - zgw
      - objecten
    ports:
      - "54324:5435"
    environment:
      - POSTGRES_USER=objecttypes
      - POSTGRES_PASSWORD=objecttypes
      - POSTGRES_DB=objecttypes

  objecttypen-api-import:
    image: maykinmedia/objecttypes-api:2.1.0
    container_name: example-objecttypen-api-import
    platform: linux/amd64
    profiles:
      - zgw
      - objecten
    environment: *objecttypes-env
    command: sh init/init.sh
    volumes:
      - ./docker/imports/objecttypes-api/fixtures:/app/src/objecttypes/fixtures
      - ./docker/imports/objecttypes-api/init:/app/init
    depends_on:
      - objecttypen-api

  open-notificaties-rabbitmq:
    image: rabbitmq:3.9-management
    container_name: example-open-notificaties-rabbitmq
    profiles:
      - zgw
    ports:
      - "5673:5672"
      - "15673:15672"

  open-notificaties-celery:
    image: openzaak/open-notificaties:1.4.3
    container_name: example-open-notificaties
    platform: linux/amd64
    profiles:
      - zgw
    environment: &notificaties-env
      - DJANGO_SETTINGS_MODULE=nrc.conf.docker
      - SECRET_KEY=${SECRET_KEY:-4wHY2Cp5`4(q%)]cuWxPQJRp5kN?g+`.Xah>%6Fsq6+)R>p_}
      - ALLOWED_HOSTS=*
      - CACHE_DEFAULT=open-notificaties-redis:6379/0
      - CACHE_AXES=open-notificaties-redis:6379/1
      - DB_PORT=5436
      - DB_HOST=open-notificaties-database
      - DB_NAME=notifications
      - DB_USER=notifications
      - DB_PASSWORD=notifications
      - DEBUG=true
      - RABBITMQ_HOST=open-notificaties-rabbitmq
      - PUBLISH_BROKER_URL=redis://open-notificaties-redis:6379/0
      - CELERY_BROKER_URL=redis://open-notificaties-redis:6379/0
      - CELERY_RESULT_BACKEND=redis://open-notificaties-redis:6379/0
      - CELERY_LOGLEVEL=DEBUG
      - CELERY_WORKER_CONCURRENCY=${CELERY_WORKER_CONCURRENCY:-4}
      - SUBPATH=${SUBPATH:-/}
    command: /celery_worker.sh
    depends_on:
      - open-notificaties-database
      - open-notificaties-rabbitmq
      - open-notificaties-redis

  open-notificaties:
    image: openzaak/open-notificaties:1.4.3
    container_name: example-open-notificaties-celery
    platform: linux/amd64
    profiles:
      - zgw
    ports:
      - "8002:8000"
    environment: *notificaties-env
    depends_on:
      - open-notificaties-database
      - open-notificaties-rabbitmq
      - open-notificaties-redis

  open-notificaties-database:
    image: postgres:13.5  # open-notificaties doesn't work with postgres 14.
    container_name: example-open-notificaties-database
    profiles:
      - zgw
    ports:
      - "54319:5436"
    environment:
      - POSTGRES_USER=${DB_USER:-notifications}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-notifications}
      - POSTGRES_DB=notifications
    volumes:
      - ./docker/imports/open-notificaties:/docker-entrypoint-initdb.d

  open-notificaties-redis:
    image: redis:6.2.6
    container_name: example-open-notificaties-redis
    profiles:
      - zgw

volumes:
  example-db-data: #enabled persistence
